### ISSUE TITLE
Feature: Song editor, navigation and edition using the numpad

### ISSUE THREAD

**Issue by MairusuPawa** [UltraStar-Deluxe/Play#111]
Hello!

I'm used to editing songs the way YASS streamlined it, using the numeric keypad instead of holding key modifiers. This allows for fast, one-handed editing when working on content. Would it be possible to add those bindings to USP's song editor?

The numpad is used as some sort of extension of the usual arrow keys:
- 4 and 6 move to the previous/next note on the current page
- 8 and 2 acts as page up (next), page down (previous)
- 5 plays the current selected note
- 1 and 3 moves the note left and right (by one beat, length unchanged)
- 7 and 9 shortens/lengthens the note (by one beat)
- Minus sign moves a note up a half-tone (due to the key's physical location, this makes sense)
- Plus sign moves a note down a half-tone

Here's a screenshot of YASS' bindings:

![image](https://user-images.githubusercontent.com/1774599/72462792-392afd80-37d2-11ea-8790-9caf32c3a7ce.png)

Thanks !

**Comment by achimmihca** [comment]
I implemented your requests in the above PR, except for the following

> 8 and 2 acts as page up (next), page down (previous)

I consider this not necessary in the USPlay song editor, because the viewport in USPlay song editor scrolls continuously (not limited to viewing a sentence aka. "page"). Furthermore, the viewport is updated when the next note is selected, thus you can just hit tab until you reach the next sentence.

Instead I added a new feature to fit the viewport to the selected notes (via right click in NoteArea), such that you can view only a single sentence (similar to Yass) if you want to.
This is a more general solution that is not limited to sentences. For example, you can also use this feature to first hit Ctrl+A, which selects all notes, and then fit the viewport horizontally to view all notes in the song.

**Comment by MairusuPawa** [comment]
Fantastic, thank you!
