### ISSUE TITLE
Mark songs as favorite

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#158]
Would be nice if one could mark a song as favorite. Then toggle a filter to show only favorite songs.

**Comment by Zeitless** [comment]
In a way of automatically creating/modifying a playlist named "favourites" which can be quick-accessed through a keyboard shortcut?
Since there isn't a playlist-option yet for what I know I would start by adding that with a corresponding file in a subfolder like in USDX.
Then I'd just hardcode a keybind to mark a song as favourite (for example "f") and in a playlist menu one can then open the playlist. Or perhaps through ctrl+f.
Still new to the whole thing so I'm asking whether this method would be okay before commiting to it.

**Comment by achimmihca** [comment]
This could be implemented as a special case of a more general playlist feature (I think someone mentioned this before?). For example, a keyboard shortcut could add the current song to the "Favorites" playlist.

A playlist here means a list of unambiguous songs, which means it is necessary to decide how to identify songs. Thus, this issue is blocked by #153.

---
I suggest to have playlists as plaing text files in the following format:

- every song in the playlist is on a separate line
- a song is identified as a combination of artist and title. This corresponds to my suggestion for #153
     - separater character could be `:` or `-` for example. I think `:` looks a bit JSON-ish, which might be good because it feels familiar.
- `#` can be used at the start of a line to indicate a comment

Example:
```
# my cool playlist
"Rammstein":"Sonne"
# this is another comment
"Rammstein":"Sonne (MTV live)"
"ABBA":"Money, money, money"
```

**Comment by achimmihca** [comment]
On a second thought, it might be better to use `-` as separating character, optionally with some space in between. Furthermore, the quotes are optional, when the separating character does not occur in the title and artist.

Example:
```
# my cool playlist
Rammstein - Sonne
# this is another comment
Rammstein - Sonne (MTV live)
ABBA - Money, money, money
# the following quotes are not optional, because - occurs in the title
"The band" - "Foo-bar"
```

This is a bit less techie notation. It's like markdown of playlist writing.

BTW:
I do not suggest to use paths for song identification in the playlist (in contrast to M3U format for example), because the paths will differ on different platforms and installation. A portable solution should be achieved if possible.
