### ISSUE TITLE
Improved UI

### ISSUE THREAD

**Issue by timgoeller** [UltraStar-Deluxe/Play#186]
I thought a bit about how the UI of Ultrastar Play could be improved. The current UI is based on the old UltraStar Deluxe interface, which feels a bit dusty by now. I think something a bit more color- and playful but clear would be nice. I made a mockup for how the main menu could look in a more modern look&feel. That kind of style could be applied to the whole program. What do you think about it? If you like it, I'll try to create a pull request that updates the application UI accordingly.

![chrome_wDz50Pewwc](https://user-images.githubusercontent.com/10633973/95021340-b2c08f80-0670-11eb-8b91-6c39590d5aa1.png)

Color palette used: https://flatuicolors.com/palette/au
Fonts used (all under Open Font License): Fredoka One, Permanent Marker

**Comment by basisbit** [comment]
@timgoeller thank you for creating that draft theme! Personally, I really like that color combination and think that this should work well for touch-input-devices as well as typical desktop targets.
How would you suggest coloring the "mouse-over"/pre-select effect - should buttons just get lighter/darker or so when you are about to select them / when they have the focus?

**Comment by timgoeller** [comment]
I think I'd use some kind of white border for hovering, like this (and maybe only a very slight color change on click):

![image](https://user-images.githubusercontent.com/10633973/95193713-89207900-07d4-11eb-88ec-23e52e35d2d3.png)

**Comment by achimmihca** [comment]
If you want to implement this, please try to make use of prefabs as much as possible.

**Comment by timgoeller** [comment]
I changed the main scene in Unity to look like the mockup. I think changing the style should be doable for the whole application. However I'm currently wondering if it might make sense to switch to the new UI Toolkit. It might be easier to switch now than having to redo everything later. What do you think?

**Comment by achimmihca** [comment]
I hope so, yes.
Especially as it seems to ship with a flex-layout engine, which probably will make layout much easier.
Furthermore, there seems to be css-ability for colors etc. I think design can be much faster iterated and polished this way.

On the other hand, it is experimental in its current state. Then again, if we would migrate later then we still would have to change everything instead of just a little.
Only thing I fear are bugs that cannot be worked around, such that one is stuck with unlucky tools.
I hope they will release UI Toolkit next year. However, Unity also took super long before releasing the new input system. Better not raise expectations too high when it comes to Unity release features.

Anyway, I think one should try the current state of UI Toolkit and see if it is well usable already.
If you want, give it a shot 👍 

---
BTW: I have some re-worked theming prototype ready to declare colors and translations in external files. If this is interesting to you, then I recommend to wait before re-doing more scenes until PR's have been merged.

**Comment by timgoeller** [comment]
Sure, I'll play around with it, and report how well it currently works! That will take some time, so waiting for the new theming is fine. This could also become easier with the new UI Toolkit and its stylesheets. Not sure yet, if these are easily replaceable on runtime. If they are, theming could simply be added by editing these stylesheet files, without the need of a theming implementation other than having the ability to specify where these stylesheets are located.

If it turns out that UI Toolkit is not stable enough yet (which is not unlikely, as you also said) it might make sense to wait for the production ready release in 2021 for a complete UI overhaul. I'm happy the help with other issues too though, as I really like the project!

**Comment by achimmihca** [comment]
> I have some re-worked theming prototype ready

The new stuff is now in the master.

@timgoeller I hope your merge conflicts are not too bad.
You might be able to copy everything under the canvas of your MainScene and paste it to the new version of the master branch.

**Comment by achimmihca** [comment]
We can use UIToolkit and the old uUI side by side. So we can migrate step by step.
At first, I would like to see UIToolkit be used in a simple menu scene (like Options or credits).
This way I can check if / how the current Theming and I18N mechanism can be applied to UIToolkit and how to do event handling.

**Comment by timgoeller** [comment]
Hey, sounds like a good idea. I'm currently writing my bachelor thesis so I'm a bit low on time. Unfortunately I haven't had the chance to dive into UIToolkit yet because of that, but I'll let you know once I did.

**Comment by achimmihca** [comment]
depends on #231

**Comment by achimmihca** [comment]
Styles can be tested on the options scenes after #264 has been merged.

@timgoeller
How was your thesis, and how is your career going?
Are you still interested in implementing this?
Regards

Adding borders to buttons and different colors should be rather simple now.

**Comment by achimmihca** [comment]
A new UI design is desirable. 
But this issue was undone for 2 years and had little results.
Can start from scratch.
