### ISSUE TITLE
SongEditor: Tap for BPM

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#208]
### Actual behaviour

To find the BPM for a new song, an external tool has to be used (see here for an example: http://www.all8.com/tools/bpm.htm).

### Expected behaviour

A button could be added to the SongEditorScene.
Clicking this button could show the clicks-per-minute.

The button has to come with an additional text.

- Initial text: "Click button to find BPM"
- After first click: "First beat"
- Afterwards it can show the computed clicks-per-minute value

Note however, that the "BPM" value in an UltraStar txt file is actually beats-per-minute divided by 4 (see BpmUtils).

Resetting the BPM counter could be done automatically after a time delay (e.g. 2 seconds) or via an additional reset button.

**Comment by basisbit** [comment]
honestly, I don't think we need the BPM feature anyways. The song editor could just always use 300 USDX-"BPM" and that will allow for fine enough syllable positioning while still not making it way too much work because of too detailled grid.
Singers will not start/stop singing notes exactly when the song beat hits anyways, so the important thing is only that the BPM is between 200 and 400. 200 tends to work better for slow songs, 400 for faster songs. Higher "BPM" makes it exponentially more work to fix the syllable timings.

**Comment by achimmihca** [comment]
Yes and no.
Yes because if the grid is fine enough then positioning notes will be possible for all songs.

However, with correct BPM "snap to grid" will work better. I mean if you need a quarter note, then you can easily set a quarter note.
Also I think with correct BPM the vertical lines provide better orientation.

Correct BPM can also benefit the singing because pitch analysis is done per-beat. Thus, having longer beats gives more samples for the beat, which can improve pitch detection.
Put the other way: if the beats are too short then pitch detection could be less accurate.
