### ISSUE TITLE
Popup with showing new version, but this is the newest version

### ISSUE THREAD

**Issue by supernevi** [UltraStar-Deluxe/Play#289]
Issue type: Bug report

### Actual behaviour
On Windows 10 64bit with the current version:

![image](https://user-images.githubusercontent.com/22367297/161712488-5cac17da-8c12-43c0-a715-be0ab238bb7a.png)

### Expected behaviour
Popup should not be shown currently and version number in left bottom corner should show the right version

### Steps to reproduce
1. Go to https://github.com/UltraStar-Deluxe/Play/releases
2. Download [StandaloneWindows64.zip](https://github.com/UltraStar-Deluxe/Play/releases/download/v0.4.0/StandaloneWindows64.zip)
3. Start the game

the commit hash seems to be right

**Comment by achimmihca** [comment]
Whoopsow! How did the wrong version number end up in the build?
Will take a look at it soon.

**Comment by l3ztum** [comment]
@achimmihca linux build is also effected
![Screenshot from 2022-04-05 16-34-27](https://user-images.githubusercontent.com/26739228/161778485-2f7823c0-f7f4-4ee1-bab7-ab675732bfb8.png)

**Comment by achimmihca** [comment]
The new GitHub Actions build artifacts have the correct version number.
I don't know what went wrong in the release.

Will check this when creating the next release.

**Comment by achimmihca** [comment]
Indeed, the new builds have again the wrong version number. It shows 0.4.0 but [VERSION.txt](https://github.com/UltraStar-Deluxe/Play/blob/master/UltraStar%20Play/Assets/VERSION.txt) already has 0.5.0.

Furthermore, the git commit hash is missing now because of a Git security update that prevents running Git commands as before.
See 
- https://stackoverflow.com/questions/71901632/fatal-unsafe-repository-home-repon-is-owned-by-someone-else
- https://github.com/game-ci/unity-builder/issues/399

Guess I have to setup docker to debug this. Sucks...
