### ISSUE TITLE
Very high gpu usage in recording settings menu.

### ISSUE THREAD

**Issue by Dampish0** [UltraStar-Deluxe/Play#310]
Issue type: Bug report

### Actual behaviour
Normal usage should be at less than 50%
![image](https://user-images.githubusercontent.com/87875399/173193224-f1b4e210-1101-4fd1-85b0-c5fcf2c8876d.png)

### Steps to reproduce
Open recording settings view

- UltraStar Play version: 0.5.0
- Windows 11 + Version	10.0.22000

**Comment by achimmihca** [comment]
Does it also happen with the built executable or only when running inside Unity Editor?

Unity Editor may do additional stuff with bad performance. If this is the case, then it is probably our own extensions to the Unity Editor.

**Comment by achimmihca** [comment]
Cannot reproduce.
My GPU usage is always pretty high with built USPlay, even in MainScene it is between 5% and 30%. Might be because I am on a laptop.
However, I do not have a higher GPU usage in recording options scene.

Is your issue specific to the recording options scene or USPlay in general?
If it is a general issue, then it might just be the "normal" performance of Unity.

**Comment by achimmihca** [comment]
I also had a very high GPU usage when in Unity play mode.
It was even happening in a new, empty scene.

The issue was gone after installing a new driver for my graphics card (nvidia).
The issue appeared probably after some Windows update (using Windows 11 by now).
