### ISSUE TITLE
Advanced search UI, add an option to have sublevels for Artists / Folders / Editions / Years / Genre

### ISSUE THREAD

**Issue by BanCrash** [UltraStar-Deluxe/Play#325]
Issue type: Feature request

### Actual behaviour

When you sort by Genre for example, you have all the songs sorted but you can't easily choose a genre IMO.

### Expected behaviour

Add an option that if it's enabled, when you sort by Genre for example, it will show first the list of genres and then when you click on one of them it will show only the songs that have that genre.

This can be applied also for Artists, Folders, Editions and Years, because when you have a lot of songs this would make easier to find them.

### Alternative:
When you open the "All songs" submenu to select playlists, could show first the playlists and then show the sorted options. So if you are sorting by Genre, in that submenu it will show "All songs" "Favorites" "Rock" "Pop" etc. This would cause that you have to scroll a lot more than on the other option, but maybe it's a cleaner solution.

**Comment by achimmihca** [comment]
> So if you are sorting by Genre, in that submenu it will show "All songs" "Favorites" "Rock" "Pop" etc.

I like the idea of this filter because it would be easy to use and gives an overview of available values.

It would even be easy to implement when reusing existing search features.
For example, clicking on "Rock" could simply set a search term `genre: Rock` (you know Google has similar features, e.g. [search by filetype](https://www.google.com/search?q=ultrastar+filetype%3Apdf)). This would also teach by example, how to use the search syntax.

However, to show available filters, one has to parse the song files. This could be slow on very large song collections.

Plus, I fear that the list of possible filter values might grow large in some cases, such that it won't be very helpful then (e.g. when listing all titles). So maybe, only show the first 20 ( ? ) entries and afterwards three dots to indicate more options that are not listed.

Further, filtering by specific song properties is currently not possible via syntax, only by explicitly changing the search properties in a popup.
I thought about an advanced search syntax before (can't find the issue right now), so this would be another use case for this.

**Comment by bohning** [comment]
Reminds me of this ;-)

https://github.com/UltraStar-Deluxe/USDX/issues/568

**Comment by achimmihca** [comment]
Ahh yes, and here I was thinking about search syntax already: #265

**Comment by BanCrash** [comment]
> However, to show available filters, one has to parse the song files. This could be slow on very large song collections.

For that case a cache could be created, since it's very unusual to modificate already existing songs. It will get updated when new songs are added, and also should be an option to manually update it just in case the existing library is modificated.



> Plus, I fear that the list of possible filter values might grow large in some cases, such that it won't be very helpful then (e.g. when listing all titles). So maybe, only show the first 20 ( ? ) entries and afterwards three dots to indicate more options that are not listed.

Yep, that's why I thought of using the song selector screen since you can easily scroll already. But after seeying @bohning suggestion I think that would be awesome, however for the case that you are talking about I would add, like on the selector song, a letters wheel. So you can manually scroll to go to the option you want or simply select the letter and then select the option:
![imagen](https://user-images.githubusercontent.com/11770760/188402568-7ea2408e-9aec-4ed7-9ecf-2d8096da5762.png)
Other option would be reusing the years selection to the other filters with a collapsed menu, so you have something like this:
![imagen](https://user-images.githubusercontent.com/11770760/188404328-e909453a-c554-4ae2-ae9c-13600592c50b.png)
So when you click on a letter it will expand and show the options that have that letter.

> Reminds me of this: [UltraStar-Deluxe/USDX#568](https://github.com/UltraStar-Deluxe/USDX/issues/568) ;-)

Yes, this is would I want!

**Comment by achimmihca** [comment]
[DynamicQueryable](https://github.com/umutozel/DynamicQueryable) works like a charm!
It allows to use C# expressions in a string to query collections. Example for the song list:
```
Genre == "Rock"
1990 <= Year && Year <= 1999 and Genre == "Rock"
Video != null
Title.Contains("summer")
```

Note that C# syntax rules apply
- `Year = 1990` is an assignment, you need to use `Year == 1990`
- Uppercase/lowercase is relevant. For example, `title.contains("some")` will not work because the field is named `Title` and the method `Contains`.
- AND is written as `&&`, OR is written as `||`
- strings must be quoted
- etc.

I will add the lib to enable song search via C# expressions. And I will add a info dialog that explains basic usage.

However, I will not add a GUI like shown above to construct search expressions.
This is a game, not an enterprise application after all. I don't want to confront a user with a complex form. Futher, a GUI never allows the same level of freedom as full search expressions.

Also I think the average user does not need such an extended search. And the intrigued user will be able to understand and use C# expression syntax.

**Comment by BanCrash** [comment]
> This is a game, not an enterprise application after all. I don't want to confront a user with a complex form. Futher, a GUI never allows the same level of freedom as full search expressions.

I understand your point of view but I disagree, I have a game launcher that have both systems and I always use the gui version because I find it more easy and comfortable to use. Anyway with the expressions system this can be closed.
