### ISSUE TITLE
Errors on Android TV (Shield TV)

### ISSUE THREAD

**Issue by Daviddevits** [UltraStar-Deluxe/Play#327]
First startup play gets stuck on the loading screen. It could not create a songs dit since the logs said:

UnityEngine.AndroidJavaObject..ctor (System.IntPtr jobject) (at <f539104aafd548c39b5499d0af03181e>:0)
UnityEngine._AndroidJNIHelper.ConvertFromJNIArray[ArrayType] (System.IntPtr array) (at <f539104aafd548c39b5499d0af03181e>:0)
UnityEngine.AndroidJNIHelper.ConvertFromJNIArray[ArrayType] (System.IntPtr array) (at <f539104aafd548c39b5499d0af03181e>:0)
UnityEngine.AndroidJavaObject.FromJavaArrayDeleteLocalRef[ReturnType] (System.IntPtr jobject) (at <f539104aafd548c39b5499d0af03181e>:0)
UnityEngine.AndroidJavaObject._Call[ReturnType] (System.String methodName, System.Object[] args) (at <f539104aafd548c39b5499d0af03181e>:0)
UnityEngine.AndroidJavaObject.Call[ReturnType] (System.String methodName, System.Object[] args) (at <f539104aafd548c39b5499d0af03181e>:0)
AndroidUtils.GetAppSpecificStorageAbsolutePath (System.Boolean sdCard) (at <726881d5c0f2479887e0e6f9887f5454>:0)
LoadingSceneControl.CreateInitialSongFolders () (at <a8a42bc48e1c433a97d1c104e858e464>:0)
LoadingSceneControl.Start () (at <a8a42bc48e1c433a97d1c104e858e464>:0)

Editing the settings.json myself and adding /storage/emulated/0/Android/data/com.Karaoke.UltraStarPlay/Songs to songDirs solved this. (not the app can not access anything other then inside /storage/emulated/0/Android/data/com.Karaoke.UltraStarPlay/ but i guess thats normal recent android behaviour)
So nowplay can start but when going in the song dirs setting in the gui: its impossible to choose a song in the input menu with a gamedpad controller.

Then i get erros trying to play a song with the mp4 video with h264

2022-10-05 22:34:20.982 [ERR] VideoPlayer cannot play url : file:///storage/emulated/0/Android/data/com.Karaoke.UltraStarPlay/Songs/SingStar Amped/Alice in Chains - Would/Alice in Chains - Would [VD#0].mp4

path seems corect and the txt, mp3 file and jpg in the same folder get loaded. Any ideas what i'm missing here?

**Comment by achimmihca** [comment]
Thanks for the detailed bug report.

mp4 should also work on Android (but not on Linux). See [Unity docs](https://docs.unity3d.com/Manual/VideoSources-FileCompatibility.html#CompatibilityWithTargetPlatforms). I already tested this successfully.

Shield TV was made for streaming, so I guess it also should support mp4 natively.

`AndroidUtils.GetAppSpecificStorageAbsolutePath` does some native calls to find the path where the app should be allowed to access files on SD card. File access is restricted on modern Android.
I think in your case, it should have returned `/storage/emulated/0/Android/data/com.Karaoke.UltraStarPlay`.

> Any ideas what i'm missing here?

I fear Shield TV may implement things differently from other Android devices, which is why it did not work for you.
Not sure what is wrong on your device. Does it work with webm video instead of mp4?

> its impossible to choose a song in the input menu with a gamedpad controller.

Well, there is no file browser (#315). The text field is intended for copy&paste.

Also, there were some issues with gamepad navigation that should be better now. But for editing text fields, you still need a keyboard.

**Comment by basisbit** [comment]
Mp4 is only the container format. It can hold frame data which is for example encoded using VP8, h264 or similar.
Unity supports reading mp4 on all platforms. However it relies on the operatong system to provide decoder support. On Android, that very much depends on vendor, drivers and hardware acceleration support. That is nothing we can influence.

**Comment by achimmihca** [comment]
Media file support will be improved with #362
