### ISSUE TITLE
Remove voice from songs using audio filters

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#345]
### Actual behaviour

For a classic karaoke experience, one has to create a dedicated version of the song file without the voice.

### Expected behaviour

UltraStar Play could feature an option that attempts to mute (at least reduce) the voice in the audio file.
Software like [Karaoke Sound Tools 3](https://www.powerkaraoke.com/src/prod_karaokesoundtools.php) offer such a feature.

### Implementation
I think, a common way to implement this is by filtering the frequency range of human voice.
Such an [audio filter](https://docs.unity3d.com/Manual/class-AudioEffect.html) might be easy to set up in Unity.

**Comment by DerDorius** [comment]
Filter make the song Quality worse, i dont know if its possible to implement:
https://github.com/deezer/spleeter

Spleeter is [Deezer](https://www.deezer.com/) source separation library with pretrained models written in [Python](https://www.python.org/) and uses [Tensorflow](https://tensorflow.org/). It makes it easy to train source separation model (assuming you have a dataset of isolated sources), and provides already trained state of the art model for performing various flavour of separation :

- Vocals (singing voice) / accompaniment separation ([2 stems](https://github.com/deezer/spleeter/wiki/2.-Getting-started#using-2stems-model))
- Vocals / drums / bass / other separation ([4 stems](https://github.com/deezer/spleeter/wiki/2.-Getting-started#using-4stems-model))
- Vocals / drums / bass / piano / other separation ([5 stems](https://github.com/deezer/spleeter/wiki/2.-Getting-started#using-5stems-model))

2 stems and 4 stems models have [high performances](https://github.com/deezer/spleeter/wiki/Separation-Performances) on the [musdb](https://sigsep.github.io/datasets/musdb.html) dataset. Spleeter is also very fast as it can perform separation of audio files to 4 stems 100x faster than real-time when run on a GPU.

We designed Spleeter so you can use it straight from [command line](https://github.com/deezer/spleeter/wiki/2.-Getting-started#usage) as well as directly in your own development pipeline as a [Python library](https://github.com/deezer/spleeter/wiki/4.-API-Reference#separator). It can be installed with [pip](https://github.com/deezer/spleeter/wiki/1.-Installation#using-pip) or be used with [Docker](https://github.com/deezer/spleeter/wiki/2.-Getting-started#using-docker-image).



And if that works it would be great for automatic Pitch detection when making Songs, because you could have the Voice only to detect the original Pitch

**Comment by achimmihca** [comment]
Integrating Spleeter has its own issue (#106). It is much more difficult to integrate in UltraStar Play because of different programming language and environment.

In contrast, this issue here is specifically for a simple audio filter, which might be trivial to implement in Unity and could provide usable quality for basic karaoke.

**Comment by basisbit** [comment]
Just a small fyi / my two cents: we implemented such a feature in UltraStar Deluxe, and did not see it being usable in the wild. We decided to not move this feature out of the "experimental" phase, because its audio quality is just too bad and at the same time it caused people to put less effort into making high quality song packages. Also, **[feature creep](https://en.wikipedia.org/wiki/Feature_creep)**

**Comment by achimmihca** [comment]
I did some tests with the approach using Audacity ( https://manual.audacityteam.org/man/vocal_reduction_and_isolation.html ).
The results are pretty bad. I think Karaoke Sound Tools 3 does something else, maybe also an AI approach.

Anyway, I will close this issue. The result is not worth it.
Spleeter (or similar AI approach) seems to be the way to go.
