### ISSUE TITLE
Change the MIDI-out device in Song Editor

### ISSUE THREAD

**Issue by bigboss97** [UltraStar-Deluxe/Play#377]
Issue type: Development discussion

I want to use another MIDI-output device in the song editor, but I couldn't find the option.
So, I use the program MIDIMapper trying to map to another MIDI device. Unfortunately, it didn't work.

### Problem or question to be solved
Does the song editor send MIDI messages to "Microsoft MIDI Mapper" or a different MIDI-output is used?

### Suggested solution/s
Allow user to select a different MIDI-output device.

### Your opinion on the topic
This option is not frequently use. Therefore it doesn't have to be in the GUI. It can be somewhere in a config file or registry.

**Comment by achimmihca** [comment]
In the current setup it is not possible to let another system synthesize audio from MIDI events.
At the moment, the audio is generated within UltraStar Play itself using a soundfont file and [CSharpSynth](https://github.com/UltraStar-Deluxe/CSharpSynthForUnity.git) (see `MidiManager.cs`).

But I agree that such an option would be nice. The MIDI output is not very high-quality at the moment.

**Comment by bigboss97** [comment]
Thank you for your quick response.
Since UltraStar songs have all the note/MIDI information it would be great if the MIDI channel can be freely diverted to any MIDI device, I'm think of lighting control. For instance, when a song is played and players are singing the MIDI track can be piped to an external MIDI device to control party lights. 

The player is controlling the notes in real-time anyway. It shouldn't be too difficult to send the notes to a MIDI device  :-)

**Comment by achimmihca** [comment]
Unity itself does not come with MIDI support. However, there are third party libraries:
- https://forum.unity.com/threads/midi-support-api.512104/
- https://github.com/atsushieno/managed-midi

One would have to check if these meet our requirements and if yes, integrate them in UltraStar Play.
Overall, this would be "nice to have", it's not a prio for me at the moment.

> to control party lights

I recommend to use a solution that uses a mic to record the music instead of MIDI events.

Maybe use a [projector](https://www.musicbeam.org) or build something with LEDs like on [YouTube](https://www.youtube.com/watch?v=lV_H5IEj0Yg). There are also music reactive LEDs on [Amazon](https://www.amazon.com/s?k=music+reactive+led).

These fun lights can be built very cheaply as DIY.

**Comment by bigboss97** [comment]
> Unity itself does not come with MIDI support. However, there are third party libraries:
OK, then it's not an option. Thanks for the information.

**Comment by achimmihca** [comment]
The Steam release will include an option to change the soundfount.
Furthermore, it will include an updated version of the MIDI lib that fixes several issues.

**Comment by achimmihca** [comment]
The MIDI output sound can now be changed via Soundfont.

Changing the MIDI out-device is out of scope unfortunately.
That said, most users seem to use regular audio files anyway. So this is probably not a big issue.

> I'm think of lighting control. For instance, when a song is played and players are singing the MIDI track can be piped to an external MIDI device to control party lights.

There are [software](https://www.musicbeam.org/) and [gadgets](https://www.youtube.com/results?search_query=led+music+visualizer) that can do this from regular audio output, so no MIDI needed in the first place.
