### ISSUE TITLE
Missing Unity Assets List

### ISSUE THREAD

**Issue by Gamerios** [UltraStar-Deluxe/Play#505]
Issue type: Bug report

### Actual behaviour
Missing Asset for Goldennoteeffect and other effect of 
Background Bokeh VFX
CartoonVFX9X
Confetti FX Pro
Hovl Studio
JMO Assets
Samples

and others needed for make Ultrastar Play work like it should.

### Expected behaviour

Can you gave all of us the link to the unity assets the are needed to buy or free ones that can use as replace not works like needed as scripts missing and so on.

Also the songeditor dont show like in Melody Mania how can fix in Ultrastar Play that it works used already all streaming assets from Melody Mania for test also downloaded from github missing streaming assets of the Developers for SPeech and  VOce Recognition but not work still not displays something in the song editior.

### Steps to reproduce
use Ultrastar Play Source code and start unity this missing assets then only much things PINK in Game

thanks

regrads

**Comment by achimmihca** [comment]
Clones #437

Unfortunately, the assets from the Unity Asset Store cannot be shared here due to their license.
That said, you should be able to find them when searching their name.

Better would be to create new assets for UltraStar Play and share them with an appropriate MIT or Creative Commons license.
The missing assets are mostly a handful of image assets.

> the songeditor dont show like in Melody Mania how can fix in Ultrastar Play that it works

Don't know. What is the error message, what is actual and expected behavior?

>  also downloaded from github missing streaming assets of the Developers for SPeech and VOce Recognition

Better would be to come up with a better integration for AI tools, see #439

**Comment by Gamerios** [comment]
yes tryed search much with the name but this developers assets creators have so much assets dont know which need buy of them that was used not want that you share them only linkt to unity store that we all here can buy them or if free download them at unity asset store 

thanks

regrads

**Comment by achimmihca** [comment]
These are the ones used in Melody Mania:

- Background Bokeh VFX: https://assetstore.unity.com/packages/p/background-bokeh-vfx-147542
- CartoonVFX9X: https://assetstore.unity.com/packages/vfx/particles/fire-explosions/fireworks-effect-2d-227132
- Confetti FX Pro: https://assetstore.unity.com/packages/vfx/particles/confetti-fx-pro-158889
- Hovl Studio: https://assetstore.unity.com/packages/vfx/particles/spells/toon-projectiles-158199
- JMO Assets: https://assetstore.unity.com/packages/vfx/particles/cartoon-fx-remaster-free-109565
- WebView: https://assetstore.unity.com/packages/tools/gui/3d-webview-for-windows-and-macos-web-browser-154144
- VLC: https://www.videolan.org/developers/unity.html
  - Not available on Asset Store anymore

Not 100% which version though because Unity does not specify these as proper dependency, it just imports their files. Personally, I think Unity has terrible dependency management.

Hope this helps!
