### ISSUE TITLE
Multiplatforms Problems

### ISSUE THREAD

**Issue by Gamerios** [UltraStar-Deluxe/Play#506]
Issue type: Development discussion

### 

How can use UltraStar Play at other Platforms like Android, Xbox with UWP or at Nintendo Switch, Playstations

Have only problems when try build it for such.

Because at UWP at Xbox only 1 Microphone works but in settings both recogniced but not at Song selection pr while Play

Also at Nintendo Switch only get White Background  only the cursor but nothing else no errors or something.

Also tryed at Playstation 4 then get error crash at start but one time had also menu but same all white like at the Nintendo Switch also no background sound or anything

Cant test at Playstation 5 because not have

At Android black background and other things not work so has ah problem with Zip Extract when download from github the Demo Songs from Ultrastar.

And you know why at WebGL not work get only error but not shich and where can fix only DLL error

Want use it at good platforms for use it nearly at all consoles or devices here.

Also great will it be if for tvOS if work.

Other Unity games i tryed work at every platforms.

thanks to all for informations

regrads

**Comment by basisbit** [comment]
I'll close this issue, because it unfortunately is not helpful at all, does not provide any details about the problems and we aren't able to resolve this issue any time soon.
To build for Playstation, Xbox and Nintendo Switch, you need to be working for a company which already developed some bigger titles, have a commercial Unity license and be certified by Unity for those platforms. In that case, you should be able to more likely figure out by yourself what might be the issue, rather than asking us who don't have any way of developing for those platforms.

> only 1 Microphone works

That is a limitation of Unity and already is tracked in other issues. With you obviously having good contact to Unity, please bring up the issue of Unity framework only providing access to one sound channel on these platforms.
