### ISSUE TITLE
create UI concept targeting first minimal release version

### ISSUE THREAD

**Issue by basisbit** [UltraStar-Deluxe/Play#9]
The goal of the first minimal release version of this game is to get some demo game working, so people get to know about this new project, come up with various use cases and piece by piece contribute to this project.

To be able to reach that goal, someone should come up with a rough UI design / layout for the game. This initial design most likely will be changed regularly later on, but we need some design to start with. That design should not be changed until the first minimal release version (Alpha version of this game)  is released, so all devs and artists and testers can help efficiently and do stuff, instead of discussing endlessly 😅

**Comment by barbeque-squared** [comment]
For the scoring screen, and assuming that final score is built from at least two components and we want to display those components as well, can we just start out with a big table like this?

Player | subscore_1 | ... | subscore_n | total
--- | --- | --- | --- | ---
[icon/color?] Player one | 122 | ... | 20 | 3086
[icon/color?] Spieler zwei | 6000 | ... | 200 | 8042
[icon/color?] Speler drie | 3822 | ... | 120 | 5639

In case of multiscreen, just duplicate the same table (with _all_ players) across every screen. Players are always ordered the same way. The one thing to do is make sure everything in the table fits on-screen, but that's just some simple arithmetic and I'm not too worried about usernames being cut off at this point in development (something like 16 characters should fit, I'd say anything over that is just a bonus at this point).
Will probably get messy when 8+ players, but I think for the general usecase it'll be fine?

**Comment by barbeque-squared** [comment]
For player-to-microphone binding, I have a few annoyances with the way USDX handles that. Not sure about other programs, but the annoyances are:
- I need to go through a bunch of microphones I'm not interested in to configure the ones I'm interested in (real-world: I have some fifteen "microphones" for four _actual_ microphones).
- Connecting different microphones requires me to also change things for currently-disconnected-but-still-assigned-to-a-player-number microphones
- Different _physical_ locations might require different player names, colors, icons, etc.

Maybe we could do something like this:
- You still have per-microphone settings, but you're only configuring the _hardware_, not also assigning it to some player number.
- You need to configure players upfront. Basically, a player is just a configurable thing with stuff like a name, a color, an icon and perhaps a difficulty setting.
- Hitting 'Sing' gives a screen where players can be assigned to the currently enabled microphones _that are also actually connected_. Have a little microphone bar here that oscillates on input or something so that you don't have to remember lists of "Player 1 = Pink, Player 2 = Blue, etc". Only microphones that have a player assigned will actually get used for singing. You can also quickly create new players from here (or maybe it's the only place to do so).
- Microphones can be explicitly _disabled_. This doesn't really disable them, it just makes them not show up ever on the assign-players-to-microphones screen.

**Comment by achimmihca** [comment]
> For player-to-microphone binding, I have a few annoyances with the way USDX handles that.

I agree with all of your points and tried to implement it as you described.

- mics are configured in the settings, independent of players. Mics can be enabled / disabled. Only enabled mics will be given to players.
- players can be enabled / disabled. Only enabled players show up in the song select scene.
- The song select scene shows some controls to connect players with mics. In the current implementation the first unused, connected, and enabled mic is taken automatically when a player is selected to sing the next song.

**Comment by achimmihca** [comment]
Regarding a UI concept: I think UltraStar Deluxe is giving us that. USDX has been there for quite a time and the UI is working well IMO.

So, I tried to re-create the USDX user interface. For a first minimal release version, this should suffice.
However, I do not consider persistent highscores or other statistics tables (e.g. played songs, played duration, overall accuracy) as part of the first minimal release version.
